{% set version = "2.3.0" %}

package:
  name: vmatch
  version: {{ version }}

source:
  url: http://www.vmatch.de/distributions/vmatch-{{ version }}-Linux_x86_64-64bit.tar.gz # [linux64]
  url: http://www.vmatch.de/distributions/vmatch-{{ version }}-Darwin_i386-64bit.tar.gz # [osx]
  url: http://www.vmatch.de/distributions/vmatch-{{ version }}-Windows_i686-64bit.tar.gz # [win64]

channels:
  - conda-forge
  - bioconda
  - rsat

requirements:
  run:
    - perl          >=5.10,<6

about:
  home: http://www.vmatch.de
