{% set version = "94" %}

package:
  name: perl-ensembl-core
  version: {{ version }}

source:
        git_url: https://github.com/Ensembl/ensembl.git
        git_tag: release/{{ version }}

channels:
  - conda-forge
  - bioconda
  - rsat

requirements:
  run:
    - perl          >=5.10,<6
    - perl-list-moreutils

about:
  home: https://www.ensembl.org/info/docs/api/index.html
