{% set version = "2018.08.04" %}

package:
  name: rsat
  version: {{ version }}

source:
  url: http://pedagogix-tagc.univ-mrs.fr/download_rsat/rsat_2018-08-04.tar.gz

channels:
  - rsat
  - bioconda

requirements:
  run:
    - python        >=2.7,<3

    - r-base  >=3.5,<3.6
    - r-gplots
    - r-jpeg
    - r-png
    - r-devtools
    - r-ggplot2
    - r-dynamictreecut
    - r-reshape2
    - r-dendextend
    - r-gridextra
    - r-egg
    - r-flux
    - r-zoo
    - r-rcolorbrewer
    - bioconductor-ctc
    - r-amap
    - bioconductor-qvalue


#     PERL dependencies
    - perl          >=5.10,<6
    - perl-yaml
    - perl-cgi
    - perl-statistics-distributions
    - perl-math-cdf
    - perl-algorithm-cluster
    - perl-file-spec
    - perl-posix
    - perl-data-dumper
    - perl-digest-md5-file
    - perl-io-all
    - perl-object-insideout
    - perl-class-std-fast
    - perl-gd
    - perl-dbi
    - perl-dbd-mysql
    - perl-db-file
    - perl-lwp-simple
    - perl-json
    - perl-xml-libxml
    - perl-xml-dom
    - perl-log-log4perl
    - perl-number-format
    - perl-ole-storage_lite
    - perl-spreadsheet-writeexcel
    - perl-readonly
    - perl-rest-client
    - perl-http-tiny
    - perl-lockfile-simple
    - perl-postscript-simple
 


about:
  home: http://rsat.eu
